-- MySQL Script generated by MySQL Workbench
-- 09/09/16 11:13:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profissional` (
  `id_profissional` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `telefone` BIGINT NULL,
  `email` VARCHAR(45) NULL,
  `graduacao` MEDIUMTEXT NULL,
  `anexo_graduacao` CHAR NULL,
  `especialidades` LONGTEXT NULL,
  `endereco` VARCHAR(80) NULL,
  `cidade` VARCHAR(20) NULL,
  `estado` VARCHAR(20) NULL,
  `bairro` VARCHAR(20) NULL,
  `numero` INT NULL,
  `cep` BIGINT NULL,
  `complemento` VARCHAR(45) NULL,
  `disponibilidade` CHAR NULL,
  `pagseguro` FLOAT NULL,
  `data_nascimento` DATE NULL,
  `data_cadastro` DATETIME NULL,
  `sexo` CHAR NULL,
  `valor_hora_aula` VARCHAR(20) NULL,
  `media_aval` FLOAT NULL,
  PRIMARY KEY (`id_profissional`),
  UNIQUE INDEX `idProfissional_UNIQUE` (`id_profissional` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` BIGINT NULL,
  `data_ultima_avaliacao` DATE NULL,
  `anexo_avaliacao` CHAR NULL,
  `endereco` VARCHAR(80) NULL,
  `cidade` VARCHAR(30) NULL,
  `estado` VARCHAR(20) NULL,
  `bairro` VARCHAR(20) NULL,
  `numero` INT NULL,
  `cep` BIGINT NULL,
  `complemento` VARCHAR(45) NULL,
  `disponibilidade` DATETIME NULL,
  `pagseguro` FLOAT NULL,
  `data_nascimento` DATE NULL,
  `data_cadastro` DATETIME NULL,
  `sexo` CHAR NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`id_cliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`definir_localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`definir_localidade` (
  `id_local_definido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(80) NULL,
  `cidade` VARCHAR(30) NULL,
  `estado` VARCHAR(20) NULL,
  `bairro` VARCHAR(20) NULL,
  `numero` INT NULL,
  `cep` BIGINT NULL,
  `complemento` VARCHAR(45) NULL,
  `equipamentos_disp_local` MEDIUMTEXT NULL,
  `observacoes` LONGTEXT NULL,
  `telefone` BIGINT NULL,
  `horario_funcionamento` DATETIME NULL,
  PRIMARY KEY (`id_local_definido`),
  UNIQUE INDEX `idlocal_definido_UNIQUE` (`id_local_definido` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pesquisa_de_profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pesquisa_de_profissional` (
  `cod_profissional` INT UNSIGNED NOT NULL,
  `cod_local` INT UNSIGNED NOT NULL,
  `especialidades` LONGTEXT NULL,
  `valor_hora_aula` FLOAT NULL,
  `sexo` CHAR NULL,
  INDEX `fk_idprofissional_idx` (`cod_profissional` ASC),
  INDEX `fk_local_idx` (`cod_local` ASC),
  UNIQUE INDEX `cod_profissional_UNIQUE` (`cod_profissional` ASC),
  UNIQUE INDEX `cod_local_UNIQUE` (`cod_local` ASC),
  CONSTRAINT `fk_idprofissional`
    FOREIGN KEY (`cod_profissional`)
    REFERENCES `mydb`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local`
    FOREIGN KEY (`cod_local`)
    REFERENCES `mydb`.`definir_localidade` (`id_local_definido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agendamento` (
  `id_agendamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(45) NULL,
  `data_hora` DATETIME NULL,
  `valor` INT NULL,
  `especialidade` LONGTEXT NULL,
  `cod_profissional` INT UNSIGNED NOT NULL,
  `cod_cliente` INT UNSIGNED NOT NULL,
  `duracao_aula` DATETIME NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `fk_profissional_idx` (`cod_profissional` ASC),
  INDEX `fk_cliente_idx` (`cod_cliente` ASC),
  UNIQUE INDEX `idAgendamento_UNIQUE` (`id_agendamento` ASC),
  UNIQUE INDEX `cod_profissional_UNIQUE` (`cod_profissional` ASC),
  UNIQUE INDEX `cod_cliente_UNIQUE` (`cod_cliente` ASC),
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`cod_profissional`)
    REFERENCES `mydb`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato_de_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato_de_servico` (
  `id_contrato` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NULL,
  `cod_profissional` INT UNSIGNED NOT NULL,
  `cod_cliente` INT UNSIGNED NOT NULL,
  `valor` INT NULL,
  `cod_local` INT UNSIGNED NOT NULL,
  `duracao_aula` DATETIME NULL,
  `data_pagamento` DATETIME NULL,
  `tipo_pagamento` VARCHAR(30) NULL,
  `descricao_atividades` LONGTEXT NULL,
  `regras_personline` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contrato`),
  INDEX `fk_profissional_idx` (`cod_profissional` ASC),
  INDEX `fk_cliente_idx` (`cod_cliente` ASC),
  INDEX `fk_local_idx` (`cod_local` ASC),
  UNIQUE INDEX `idContrato_UNIQUE` (`id_contrato` ASC),
  UNIQUE INDEX `cod_profissional_UNIQUE` (`cod_profissional` ASC),
  UNIQUE INDEX `cod_cliente_UNIQUE` (`cod_cliente` ASC),
  UNIQUE INDEX `cod_local_UNIQUE` (`cod_local` ASC),
  CONSTRAINT `fk_profissional2`
    FOREIGN KEY (`cod_profissional`)
    REFERENCES `mydb`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente2`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local2`
    FOREIGN KEY (`cod_local`)
    REFERENCES `mydb`.`definir_localidade` (`id_local_definido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faq` (
  `id_faq` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descricao` LONGTEXT NULL,
  `pergunta_cliente_frequente` LONGTEXT NULL,
  PRIMARY KEY (`id_faq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao` (
  `id_avaliacao` INT NOT NULL,
  `cod_cliente` INT UNSIGNED NOT NULL,
  `cod_profissional` INT UNSIGNED NOT NULL,
  `desc_aval` LONGTEXT NULL,
  `ponto` CHAR NULL,
  PRIMARY KEY (`id_avaliacao`),
  UNIQUE INDEX `cod_cliente_UNIQUE` (`cod_cliente` ASC),
  UNIQUE INDEX `cod_profissional_UNIQUE` (`cod_profissional` ASC),
  CONSTRAINT `fk_profissional3`
    FOREIGN KEY (`cod_profissional`)
    REFERENCES `mydb`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente3`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
