app:
    resource: "@AppBundle/Controller/"
    type:     annotation

Avaliacao:
    type:     rest
    resource: \Restapi\Controller\AvaliacaoController

Usuario:
    type:     rest
    resource: \Restapi\Controller\UsuarioController

Agendamento:
    type:     rest
    resource: \Restapi\Controller\AgendamentoController

ContratoDeServico:
    type:     rest
    resource: \Restapi\Controller\ContratoDeServicoController

Localidade:
    type:     rest
    resource: \Restapi\Controller\LocalidadeController

Cidade:
    type:     rest
    resource: \Restapi\Controller\CidadeController

Estado:
    type:     rest
    resource: \Restapi\Controller\EstadoController
