app:
    resource: "@AppBundle/Controller/"
    type:     annotation

Avaliacao:
    type:     rest
    resource: \Restapi\Controller\AvaliacaoController

Usuario:
    type:     rest
    resource: \Restapi\Controller\UsuarioController
